### ISSUE TITLE
Compilation Failed To Complete

### ISSUE THREAD

**Issue by Monim64** [uttesh/exude#6]
When I add your library in my project, I am getting this error.

**Program type already present: org.apache.commons.logging.Log
Message{kind=ERROR, text=Program type already present: org.apache.commons.logging.Log, sources=[Unknown source file], tool name=Optional.of(D8)}**

Can you help me with this problem?

![1](https://user-images.githubusercontent.com/11071917/38925644-0f0a07fe-4322-11e8-9cec-c28b57cfbce9.JPG)

![2](https://user-images.githubusercontent.com/11071917/38925653-190f306c-4322-11e8-967b-ab5a868fb0ad.JPG)

**Comment by uttesh** [comment]
@Monim64 

exclude the libraries which are already present, [https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991](url)

`compile('com.uttesh.exude:0.0.3') {
     exclude group: 'org.unwanted', module: 'x 
  }`

its nothing to do with the library, closing the issue.
